new: Got rid of calling built-in function printf() by a binary.

diff --git a/lib/core b/lib/core
--- a/lib/core
+++ b/lib/core
@@ -9,7 +9,7 @@ mkdir -p "${DEFAULT_LOGDIR}"
 
 debug () {
     if [ -n "${*}" ] && [ -n "${DEBUG}" ]; then
-        ${PRINTF_BIN} "#%b%s%b\n" "${ColorDebug}" "${@}" "${ColorReset}" >&2
+        printf "#%b%s%b\n" "${ColorDebug}" "${@}" "${ColorReset}" >&2
     fi
     return 0
 }
@@ -17,9 +17,9 @@ debug () {
 
 warn () {
     if [ -n "${*}" ]; then
-        ${PRINTF_BIN} "\n%b%s%b\n\n" "${ColorYellow}" "${@}" "${ColorReset}" >&2
+        printf "\n%b%s%b\n\n" "${ColorYellow}" "${@}" "${ColorReset}" >&2
     else
-        ${PRINTF_BIN} "\n"
+        printf "\n"
     fi
     return 0
 }
@@ -27,9 +27,9 @@ warn () {
 
 note () {
     if [ -n "${*}" ]; then
-        ${PRINTF_BIN} "\n%b%s%b\n" "${ColorGreen}" "${@}" "${ColorReset}" >&2
+        printf "\n%b%s%b\n" "${ColorGreen}" "${@}" "${ColorReset}" >&2
     else
-        ${PRINTF_BIN} "\n"
+        printf "\n"
     fi
     return 0
 }
@@ -37,7 +37,7 @@ note () {
 
 progress_note () {
     if [ -n "${*}" ]; then
-        ${PRINTF_BIN} "${REPLAY_PREVIOUS_LINE}%b%s%b\n" "${ColorGreen}" "${@}" "${ColorReset}" >&2
+        printf "${REPLAY_PREVIOUS_LINE}%b%s%b\n" "${ColorGreen}" "${@}" "${ColorReset}" >&2
     fi
     return 0
 }
@@ -45,34 +45,34 @@ progress_note () {
 
 error () {
     if [ -n "${*}" ]; then
-        ${PRINTF_BIN} "%b\n  %s %s\n    %b %b\n\n" "${ColorRed}" "${NoteChar}" "Task crashed!" "${0}: ${1}${2}${3}${4}${5}" "${ColorReset}" >&2
+        printf "%b\n  %s %s\n    %b %b\n\n" "${ColorRed}" "${NoteChar}" "Task crashed!" "${0}: ${1}${2}${3}${4}${5}" "${ColorReset}" >&2
     else
-        ${PRINTF_BIN} "%b\n  %s%b\n" "${ColorRed}" "ERROR!" "${ColorReset}" >&2
+        printf "%b\n  %s%b\n" "${ColorRed}" "ERROR!" "${ColorReset}" >&2
     fi
     exit 1
 }
 
 
 distd () {
-    ${PRINTF_BIN} "%b%s%b" "${2:-${ColorDistinct}}" "${1}" "${3:-${ColorDebug}}" 2>/dev/null
+    printf "%b%s%b" "${2:-${ColorDistinct}}" "${1}" "${3:-${ColorDebug}}" 2>/dev/null
     return 0
 }
 
 
 distn () {
-    ${PRINTF_BIN} "%b%s%b" "${2:-${ColorDistinct}}" "${1}" "${3:-${ColorNote}}" 2>/dev/null
+    printf "%b%s%b" "${2:-${ColorDistinct}}" "${1}" "${3:-${ColorNote}}" 2>/dev/null
     return 0
 }
 
 
 distw () {
-    ${PRINTF_BIN} "%b%s%b" "${2:-${ColorDistinct}}" "${1}" "${3:-${ColorWarning}}" 2>/dev/null
+    printf "%b%s%b" "${2:-${ColorDistinct}}" "${1}" "${3:-${ColorWarning}}" 2>/dev/null
     return 0
 }
 
 
 diste () {
-    ${PRINTF_BIN} "%b%s%b" "${2:-${ColorDistinct}}" "${1}" "${3:-${ColorError}}" 2>/dev/null
+    printf "%b%s%b" "${2:-${ColorDistinct}}" "${1}" "${3:-${ColorError}}" 2>/dev/null
     return 0
 }
 
@@ -80,7 +80,7 @@ diste () {
 # Make a varname from params
 make_var_name () {
     if [ -n "${*}" ]; then
-        ${PRINTF_BIN} "%s\n" "${*}" | ${SED_BIN} 's#[ ;:=%_/.-]#_#g' 2>/dev/null
+        printf "%s\n" "${*}" | ${SED_BIN} 's#[ ;:=%_/.-]#_#g' 2>/dev/null
     fi
 }
 
@@ -88,7 +88,7 @@ make_var_name () {
 # Make a varname from param and return held value
 get_var_value () {
     if [ -n "${1}" ]; then
-        eval "${PRINTF_BIN} '%s\n' \"\$$(make_var_name "${1}")\""
+        eval "printf '%s\n' \"\$$(make_var_name "${1}")\""
     fi
 }
 
@@ -177,7 +177,7 @@ await_async () {
 
                 if [ -f "${_plog}.error" ] && [ -n "$(${CAT_BIN} "${_plog}.error" 2>/dev/null)" ]; then
                     warn "===>  Showing error log: $(distn "${_plog}")"
-                    ${PRINTF_BIN} "%b\n%s %s\n    %b %b\n\n" "${ColorRed}" "${NoteChar}" "StdERR:" "$(${CAT_BIN} "${_plog}.error")" "${ColorReset}"
+                    printf "%b\n%s %s\n    %b %b\n\n" "${ColorRed}" "${NoteChar}" "StdERR:" "$(${CAT_BIN} "${_plog}.error")" "${ColorReset}"
                 fi
                 note "==================================================================================="
                 note
@@ -192,7 +192,7 @@ await_async () {
 # validate environment availability or crash
 validate_env () {
     for _envvar in $(${CAT_BIN} lib/vars 2>/dev/null | ${GREP_BIN} -E "^.*[A-Z]+_BIN=\"\/.*\/.*\"" 2>/dev/null); do
-        _vname="$(${PRINTF_BIN} '%s' "${_envvar}" | ${SED_BIN} 's/=.*$//' 2>/dev/null)"
+        _vname="$(printf '%s' "${_envvar}" | ${SED_BIN} 's/=.*$//' 2>/dev/null)"
         if [ -n "${_vname}" ]; then
             _val="$(eval "echo \$${_vname}")"
         else
